# Generated by Django 6.1.1 on 2026-10-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastereport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='wastereport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
