"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

from pathlib import Path
import os

from dotenv import load_dotenv
import dj_database_url


# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# ============================================================
# SECURITY SETTINGS
# ============================================================

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-development-key'
)

DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'


# Allowed hosts for local development
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
]

# Render provides the public hostname automatically.
RENDER_EXTERNAL_HOSTNAME = os.environ.get(
    'RENDER_EXTERNAL_HOSTNAME'
)

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# CSRF trusted origins
CSRF_TRUSTED_ORIGINS = [
    'https://sizaclean.onrender.com',
]

if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(
        f'https://{RENDER_EXTERNAL_HOSTNAME}'
    )

# ============================================================
# APPLICATION DEFINITION
# ============================================================
INSTALLED_APPS = [
    'daphne',
    'cloudinary_storage',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'channels',
    'cloudinary',
    'waste_reports',
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    # Serve static files in production.
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# URL CONFIGURATION
# ============================================================

ROOT_URLCONF = 'config.urls'


# ============================================================
# TEMPLATE SETTINGS
# ============================================================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [

                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            ],
        },
    },
]


# ============================================================
# WSGI / ASGI APPLICATION
# ============================================================

WSGI_APPLICATION = 'config.wsgi.application'

ASGI_APPLICATION = 'config.asgi.application'


# ============================================================
# DATABASE
# ============================================================

# If DATABASE_URL exists, use the online PostgreSQL database.
# Otherwise, use the existing local MySQL database.

if os.environ.get('DATABASE_URL'):

    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }

else:

    DATABASES = {
        'default': {
            'ENGINE': os.environ.get(
                'DB_ENGINE',
                'django.db.backends.mysql'
            ),

            'NAME': os.environ.get(
                'DB_NAME',
                'sizaclean_db'
            ),

            'USER': os.environ.get(
                'DB_USER',
                'sizaclean_user'
            ),

            'PASSWORD': os.environ.get(
                'DB_PASSWORD',
                ''
            ),

            'HOST': os.environ.get(
                'DB_HOST',
                'localhost'
            ),

            'PORT': os.environ.get(
                'DB_PORT',
                '3306'
            ),
        }
    }


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
        'django.contrib.auth.password_validation.'
        'UserAttributeSimilarityValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.'
        'MinimumLengthValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.'
        'CommonPasswordValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.'
        'NumericPasswordValidator',
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg'

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },

    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Required by django-cloudinary-storage 0.3.0
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# ============================================================
# EMAIL SSTORAGEETTINGS
# ============================================================

# Console email backend is used during development.
# Password reset emails appear in the VS Code terminal.

EMAIL_BACKEND = (
    'django.core.mail.backends.console.EmailBackend'
)

DEFAULT_FROM_EMAIL = 'noreply@sizaclean.local'


# ============================================================
# MEDIA FILES
# ============================================================

# Cloudinary configuration for uploaded report photos
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================
# DATABASE / CHANNEL SETTINGS
# ============================================================

CHANNEL_LAYERS = {
    'default': {
        'BACKEND':
        'channels.layers.InMemoryChannelLayer',
    },
}


# ============================================================
# DEFAULT PRIMARY KEY
# ============================================================

DEFAULT_AUTO_FIELD = (
    'django.db.models.BigAutoField'
)


# ============================================================
# LOGIN REDIRECT
# ============================================================

LOGIN_URL = '/login/'


# ============================================================
# PRODUCTION SECURITY
# ============================================================

if not DEBUG:

    SECURE_PROXY_SSL_HEADER = (
        'HTTP_X_FORWARDED_PROTO',
        'https'
    )

    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SECURE = True